name: Build and Test Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install

      - name: Executa testes se existirem
        run: |
          if ls __tests__/*.test.js 1> /dev/null 2>&1; then
            echo "Testes encontrados. Executando npm test..."
            npm test
          else
            echo "Nenhum teste encontrado. Etapa de testes ignorada."
          fi
