name: Build and Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build if script exists
        run: |
          if npm run | grep -q "build"; then
            echo "Script de build encontrado. Executando build..."
            npm run build
          else
            echo "Script de build não encontrado no package.json. Pulando etapa."
          fi

      - name: Upload production build as artifact
        if: success() && steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist
